### ISSUE TITLE
works? kind of

### ISSUE THREAD

**Issue by powerdollkirby** [RandomGamingDev/yt-times#1]
![image](https://github.com/user-attachments/assets/3e45ed7e-27d9-4a70-bff1-46fb5a8b4c7a)

**Comment by RandomGamingDev** [comment]
Hmmm weird.
What version of firefox are you using, device are you running it on, and what version of the Youtube UI are you using? I don't think I've seen that UI on modern youtube before.
Other than that, a note is that despite the time updating nearly instantly, if your connection with youtube gets stalled for some reason you'll also see a cut off in the transformations of video release time conversions from relative to static.

**Comment by powerdollkirby** [comment]
> Hmmm weird.
> 
> What version of firefox are you using, device are you running it on, and what version of the Youtube UI are you using? I don't think I've seen that UI on modern youtube before.
> 
> Other than that, a note is that despite the time updating nearly instantly, if your connection with youtube gets stalled for some reason you'll also see a cut off in the transformations of video release time conversions from relative to static.

latest ff 128.0 and youtube redux 2005 layout, but i highly doubt that's breaking it

**Comment by RandomGamingDev** [comment]
> latest ff 128.0 and youtube redux 2005 layout, but i highly doubt that's breaking it

Mobile or desktop and have you tried without the Youtube Redux 2005 layout?

**Comment by powerdollkirby** [comment]
> > latest ff 128.0 and youtube redux 2005 layout, but i highly doubt that's breaking it
> 
> Mobile or desktop and have you tried without the Youtube Redux 2005 layout?

desktop, and yes, i just did and same behaviour, works for some videos

**Comment by RandomGamingDev** [comment]
> desktop, and yes, i just did and same behaviour, works for some videos

What other extensions do you have and could you send another screenshot with the modern Youtube UI?

**Comment by powerdollkirby** [comment]
looks/performs the same, some videos get the date changed, the rest don't
it also struggles a lot in the home page so most of the time won't work there, just in the search results, most of the time
and i don't have any other extension that interferes with youtube.com just ublock and tempermonkey with [this script ](https://greasyfork.org/en/scripts/482977-remove-youtube-tracking-parameters-and-convert-share-links)
![image](https://github.com/user-attachments/assets/b2cfbc92-8be9-4455-95d0-8fe366b9e677)

**Comment by powerdollkirby** [comment]
now see here my feed with redux enabled
![image](https://github.com/user-attachments/assets/c136c9ed-6887-44c8-b80f-eb8b6b33bf66)

**Comment by RandomGamingDev** [comment]
Could you send the console logs or even better send the messages specifically outputted by the Youtube Times extension?
Sorry about all the questions, but I haven't seen this happening on any of my other devices so I'm not sure what could be causing this.

**Comment by powerdollkirby** [comment]
> Could you send the console logs or even better send the messages specifically outputted by the Youtube Times extension? Sorry about all the questions, but I haven't seen this happening on any of my other devices so I'm not sure what could be causing this.


errors:
TypeError: html.querySelectorAll(...)[0] is undefined[main.js:4:63](moz-extension://b9ae505e-8cda-44e7-b917-4e21c9b0b096/main.js)

    get_date_published moz-extension://b9ae505e-8cda-44e7-b917-4e21c9b0b096/main.js:4
    replace_dates moz-extension://b9ae505e-8cda-44e7-b917-4e21c9b0b096/main.js:111
    <anonymous> moz-extension://b9ae505e-8cda-44e7-b917-4e21c9b0b096/main.js:130

TypeError: NetworkError when attempting to fetch resource. 24 main.js:12:18

**Comment by RandomGamingDev** [comment]
> > Could you send the console logs or even better send the messages specifically outputted by the Youtube Times extension? Sorry about all the questions, but I haven't seen this happening on any of my other devices so I'm not sure what could be causing this.
> 
> errors: TypeError: html.querySelectorAll(...)[0] is undefinedmain.js:4:63
> 
> ```
> get_date_published moz-extension://b9ae505e-8cda-44e7-b917-4e21c9b0b096/main.js:4
> replace_dates moz-extension://b9ae505e-8cda-44e7-b917-4e21c9b0b096/main.js:111
> <anonymous> moz-extension://b9ae505e-8cda-44e7-b917-4e21c9b0b096/main.js:130
> ```
> 
> TypeError: NetworkError when attempting to fetch resource. 24 main.js:12:18

From what I see it still looks like it's a layout issue since selecting the element on my devices with the vanilla Youtube UI doesn't have an issue. I tried adding a try catch so try downloading and from the repo or waiting for the update to version `1.0.3` on the extensions page and then update and test it.

**Comment by powerdollkirby** [comment]
well i tried it without any yt modifications and still happening, so no worries i'll just wait if you get to fix it

**Comment by RandomGamingDev** [comment]
> well i tried it without any yt modifications and still happening, so no worries i'll just wait if you get to fix it

That's what I tried to do with version `1.0.3` mentioned in the [msg above](https://github.com/RandomGamingDev/yt-times/issues/1#issuecomment-2233665933). Have you tried it yet?

**Comment by powerdollkirby** [comment]
i just checked and it works on waterfox but not on firefox, with the same extensions enabled, including youtube redux and the 2005 layout

(idk wtf are those recommendations)
![image](https://github.com/user-attachments/assets/0e1b476a-ef5a-4fcd-96ac-8a55f431bc49)

**Comment by RandomGamingDev** [comment]
> i just checked and it works on waterfox but not on firefox, with the same extensions enabled, including youtube redux and the 2005 layout

Haven't heard of anyone using Waterfox in a long time. Are you using Waterfox Current or Waterfox Classic?

Also, could you try installing yt-times on an incognito window as well as reinstalling Firefox, or trying it on another device where Firefox is guaranteed to be in its default configuration?

Maybe something like user agent or something other setting could be causing the issue if you're sure that no other extensions are installed.

**Comment by powerdollkirby** [comment]
i found the problem, it's the [script](https://greasyfork.org/en/scripts/482977-remove-youtube-tracking-parameters-and-convert-share-links) i mentioned before

also yeah waterfox G6.0.17 is good

**Comment by RandomGamingDev** [comment]
> i found the problem, it's the [script](https://greasyfork.org/en/scripts/482977-remove-youtube-tracking-parameters-and-convert-share-links) i mentioned before
> 
> also yeah waterfox G6.0.17 is good

Ah alr

Now that it works I'll be closing this issue
